from pathlib import Path
path = Path('index.html')
text = path.read_text('utf-8')

# Replace meta and title
text = text.replace(
    '<meta name="description" content="Abdul-quadr Akewusola — Web2 & Web3 Social Media Manager, Community Manager and Moderator." />\n  <meta name="theme-color" content="#090914" />\n  <title>Abdul-quadr Akewusola | Web3 Community & Social Manager</title>',
    '<meta name="description" content="Akewusola Abdul-Quadri — Web3 Community Manager, Project Lead, and Discord/Telegram Moderator." />\n  <meta name="theme-color" content="#090914" />\n  <title>Akewusola Abdul-Quadri | Web3 Community Manager</title>'
)

# Replace hero CV link and copy
text = text.replace(
    '<div class="role" id="typing" aria-label="Web2 and Web3 Social Media Manager"></div><p>I help Web2 and Web3 brands grow trusted, engaged communities through smart social media, thoughtful moderation, and people-first strategy.</p><div class="hero-actions"><a href="#contact" class="btn btn-primary">Hire Me <span>↗</span></a><a href="resume.pdf" download class="btn btn-quiet">Download CV ↓</a><a href="#community" class="btn btn-quiet">Join My Community</a></div>',
    '<div class="role" id="typing" aria-label="Web3 Community Manager"></div><p>I help Web3 projects launch, grow, and keep communities active with social strategy, thoughtful moderation, and crypto-native engagement.</p><div class="hero-actions"><a href="#contact" class="btn btn-primary">Hire Me <span>↗</span></a><a href="cv.pdf" download class="btn btn-quiet">Download CV ↓</a><a href="#community" class="btn btn-quiet">Join My Community</a></div>'
)

# Replace about section
old_about = '    <section class="section container" id="about"><div class="about-grid"><div class="reveal"><span class="eyebrow">About Me</span><h2 class="heading">Communities thrive when people feel seen.</h2></div><div class="about-copy reveal"><p>I’m a social media and community professional with <strong>5+ years of experience</strong> helping brands turn followers into active communities. I bring clarity, warmth, and a measurable growth mindset to every channel.</p><p>Whether it’s supporting a customer, hosting an AMA, guiding a token launch, or shaping a content calendar, I care about building spaces that are useful, welcoming, and alive.</p><div class="mini-stats"><div class="mini-stat glass"><b>5+</b><span>Years experience</span></div><div class="mini-stat glass"><b>100K+</b><span>Members managed</span></div><div class="mini-stat glass"><b>Web2/Web3</b><span>Native mindset</span></div></div></div></div></section>'
new_about = '    <section class="section container" id="about"><div class="about-grid"><div class="reveal"><span class="eyebrow">About Me</span><h2 class="heading">Building Web3 communities that move projects forward.</h2></div><div class="about-copy reveal"><p>I’m a Web3 Community Manager and Project Lead with a proven record of building vibrant crypto communities and driving project momentum.</p><p>I combine social strategy, Discord and Telegram systems, launch execution, and member-first moderation to turn followers into active, loyal communities.</p><div class="mini-stats"><div class="mini-stat glass"><b>10K+</b><span>Members grown</span></div><div class="mini-stat glass"><b>$10M</b><span>Market cap peak</span></div><div class="mini-stat glass"><b>Discord & Telegram</b><span>Platform expertise</span></div></div></div></div></section>'
text = text.replace(old_about, new_about)

# Replace skills section completely
skills_start = text.index('section class="section skills-bg" id="skills"')
skills_end = text.index('section class="section skills-bg" id="portfolio"')
skills_block = text[skills_start:skills_end]
new_skills = '    <section class="section skills-bg" id="skills"><div class="container"><div class="reveal"><span class="eyebrow">Skills</span><h2 class="heading">A complete Web3 community toolkit.</h2><p class="intro">Community management, launch operations, moderation, and growth for crypto-native brands.</p></div><div class="skill-grid"><div class="skill glass reveal" style="--score:96%"><div class="skill-top">Community Management <span>96%</span></div><div class="bar"><i></i></div></div><div class="skill glass reveal" style="--score:95%"><div class="skill-top">Discord <span>95%</span></div><div class="bar"><i></i></div></div><div class="skill glass reveal" style="--score:94%"><div class="skill-top">Telegram <span>94%</span></div><div class="bar"><i></i></div></div><div class="skill glass reveal" style="--score:92%"><div class="skill-top">Social Analytics <span>92%</span></div><div class="bar"><i></i></div></div><div class="skill glass reveal" style="--score:91%"><div class="skill-top">Content Creation <span>91%</span></div><div class="bar"><i></i></div></div><div class="skill glass reveal" style="--score:90%"><div class="skill-top">Project Management <span>90%</span></div><div class="bar"><i></i></div></div><div class="skill glass reveal" style="--score:93%"><div class="skill-top">NFTs, Crypto & DeFi <span>93%</span></div><div class="bar"><i></i></div></div><div class="skill glass reveal" style="--score:92%"><div class="skill-top">Token Launches <span>92%</span></div><div class="bar"><i></i></div></div><div class="skill glass reveal" style="--score:95%"><div class="skill-top">Moderation <span>95%</span></div><div class="bar"><i></i></div></div><div class="skill glass reveal" style="--score:93%"><div class="skill-top">Growth Strategy <span>93%</span></div><div class="bar"><i></i></div></div><div class="skill glass reveal" style="--score:89%"><div class="skill-top">Engagement Events <span>89%</span></div><div class="bar"><i></i></div></div><div class="skill glass reveal" style="--score:88%"><div class="skill-top">Crisis Management <span>88%</span></div><div class="bar"><i></i></div></div></div></div></section>'
text = text.replace(skills_block, new_skills)

# Replace portfolio section completely
portfolio_start = text.index('section class="section skills-bg" id="portfolio"')
portfolio_end = text.index('section class="section container" id="experience"')
portfolio_block = text[portfolio_start:portfolio_end]
new_portfolio = '    <section class="section skills-bg" id="portfolio"><div class="container"><div class="reveal"><span class="eyebrow">Portfolio</span><h2 class="heading">Selected Web3 growth work.</h2><p class="intro">Real community, launch, and engagement outcomes for crypto projects.</p></div><div class="project-grid"><article class="project glass reveal"><div class="project-image"><img loading="lazy" src="https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80" alt="Web3 token launch" /></div><div class="project-body"><h3>CATVAX Community Takeover</h3><p>Led the CATVAX community takeover, built roadmap execution, and helped reach a peak $4M market cap.</p><div class="tags"><span class="tag">Discord</span><span class="tag">Launch</span><span class="tag">Fundraising</span></div><div class="project-actions"><a href="#contact">Contact ↗</a></div></div></article><article class="project glass reveal"><div class="project-image"><img loading="lazy" src="https://images.unsplash.com/photo-1515169067865-5387ec356754?auto=format&fit=crop&w=800&q=80" alt="Token community engagement" /></div><div class="project-body"><h3>$BABY Token Launch</h3><p>Managed X and Telegram presence, hosted engagement events, and supported a successful Pinksale launch.</p><div class="tags"><span class="tag">X</span><span class="tag">Telegram</span><span class="tag">Launch</span></div><div class="project-actions"><a href="#contact">Contact ↗</a></div></div></article><article class="project glass reveal"><div class="project-image"><img loading="lazy" src="https://images.unsplash.com/photo-1504386106331-3e4e71712b38?auto=format&fit=crop&w=800&q=80" alt="Community growth" /></div><div class="project-body"><h3>X Threader Growth</h3><p>Scaled Telegram from 500 to 10,000 members and X from 500 to 10,000 followers in under two months.</p><div class="tags"><span class="tag">Growth</span><span class="tag">Analytics</span><span class="tag">Engagement</span></div><div class="project-actions"><a href="#contact">Contact ↗</a></div></div></article><article class="project glass reveal"><div class="project-image"><img loading="lazy" src="https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?auto=format&fit=crop&w=800&q=80" alt="Telegram moderation" /></div><div class="project-body"><h3>Telegram Moderation System</h3><p>Built a clearer Telegram moderation workflow and member support process to protect culture and reduce noise.</p><div class="tags"><span class="tag">Telegram</span><span class="tag">Safety</span><span class="tag">Support</span></div><div class="project-actions"><a href="#contact">Contact ↗</a></div></div></article></div></div></section>'
text = text.replace(portfolio_block, new_portfolio)

# Replace experience section completely
experience_start = text.index('section class="section container" id="experience"')
experience_end = text.index('section class="achievements"')
experience_block = text[experience_start:experience_end]
new_experience = '    <section class="section container" id="experience"><div class="reveal"><span class="eyebrow">Experience</span><h2 class="heading">Work history in Web3 community growth.</h2></div><div class="timeline"><article class="timeline-item reveal"><div class="timeline-top"><div><h3>Web3 Project Lead</h3><span class="job">CATVAX CTO</span></div><span class="date">May 2024 — Present</span></div><p>Led community takeover, managed treasury and fundraising, and drove roadmap execution for a token project that reached a peak $4M market cap.</p></article><article class="timeline-item reveal"><div class="timeline-top"><div><h3>Social Media Manager</h3><span class="job">$BABY Token</span></div><span class="date">Mar 2024 — Aug 2024</span></div><p>Managed X and Telegram, hosted community events, and supported a successful Pinksale token launch.</p></article><article class="timeline-item reveal"><div class="timeline-top"><div><h3>Social Media Manager</h3><span class="job">X Threader</span></div><span class="date">Mar 2024 — May 2024</span></div><p>Scaled Telegram from 500 to 10,000 members and X from 500 to 10,000 followers while increasing engagement and community retention.</p></article></div></section>'
text = text.replace(experience_block, new_experience)

# Update contact list with actual project contacts
contact_old = '<div class="contact-list"><a href="mailto:hello@abdulqadir.com"><i>@</i>hello@abdulqadir.com</a><a href="https://x.com"><i>𝕏</i>@abdulqadir</a><a href="https://linkedin.com"><i>in</i>LinkedIn</a><a href="https://github.com"><i>GH</i>GitHub</a><a href="#community"><i>◉</i>Discord: AbdulQadir#0001</a></div>'
contact_new = '<div class="contact-list"><a href="mailto:hello@abdulqadir.com"><i>@</i>hello@abdulqadir.com</a><a href="https://x.com/MetaKay23"><i>𝕏</i>@MetaKay23</a><a href="https://linkedin.com/in/akewusola-abdul-quadri"><i>in</i>LinkedIn</a><a href="https://t.me/metakay23"><i>✈</i>Telegram</a><a href="#community"><i>◉</i>Discord: metakay23</a></div>'
text = text.replace(contact_old, contact_new)

# Save
path.write_text(text, encoding='utf-8')
print('Updated index.html successfully')
